apiVersion: v1
kind: Service
metadata:
  name: rocketdex-service
spec:
  type: NodePort
  selector:
    app: rocketdex
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000  # can be any port in 30000–32767
